#!/usr/bin/env python3
import argparse
import json
import sys
import yaml

parser = argparse.ArgumentParser()
parser.add_argument('json_file', nargs='?', type=argparse.FileType('r'), default=sys.stdin)
args = parser.parse_args()

json_body = json.load(args.json_file)
yaml_body = yaml.dump(json_body, default_flow_style=False)
print(yaml_body, end='')
